
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QiLCJpYXQiOjE2MzUwODI1NTgsImV4cCI6MTY3MTA3ODk1OH0.hODuFNFAb0i6bHuf7vsOAtKWWJzX1LzhzOEu74raTZY
@api=http://localhost:3001
### update role 
PUT {{api}}/role HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "userId": "1", 
    "role": "client"
}
### register specialist 
POST {{api}}/add-specialist HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "firstName": "test5",
    "lastName": "test5",
    "email": "test5",
    "password": "test5",
    "phone": "test5",
    "jobName": "doctor"
}

### delete speciali
DELETE {{api}}/specialist/555 HTTP/1.1
content-type: application/json
Authorization: {{token}}

