@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJlbWFpbCI6ImNsaWVudCIsImlhdCI6MTYzNTA4NDAzMiwiZXhwIjoxNjM4NjgwNDMyfQ.Vs_yqXsW5Kf5bAVZHhpIWgCW98f76642HtA3JVDOZJI
@api=http://localhost:3001

### create reservation 
POST {{api}}/reservation HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "Wizyta dentystyczna", 
    "datetime_start": "2021-10-18T22:00:00.936Z",
    "datetime_end": "2021-10-18T23:00:00.936Z"
}

